/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FORM;

import DATABASE.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Harun Ar
 */
public class FLOGIN extends javax.swing.JFrame {

    public static String userAkses;
    
    /**
     * Creates new form FLOGIN
     */
    public FLOGIN() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void aksi_login(){
        try{
            String akses = "";
            Statement st;
            ResultSet rs;
            Connection con;
            con = null;
            con = koneksi.koneksiDatabase();
            String query = "select username, password, akses "
                    + "from kasir "
                    + "where username='"+TxtUsername.getText().replaceAll("'", "")+"' "
                    + "and password='"+TxtPassword.getText().replaceAll("'", "")+"'";
            st = con.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                userAkses = rs.getString(3);
                akses = "-";
                this.setVisible(false);
                FMENU menu = new FMENU(userAkses);
                menu.setVisible(true);
            }if(akses.equals("")){
                JOptionPane.showMessageDialog(this, "Periksa kembali Username dan Password !");
            }
        }catch(Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iLOGIN1 = new FORM.ILOGIN();
        TxtUsername = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JPasswordField();
        BtnMasuk = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/GAMBAR/icon.png")).getImage());

        TxtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtUsername.setOpaque(false);

        TxtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtPassword.setOpaque(false);

        BtnMasuk.setContentAreaFilled(false);
        BtnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasukActionPerformed(evt);
            }
        });
        BtnMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnMasukKeyPressed(evt);
            }
        });

        BtnBatal.setContentAreaFilled(false);
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iLOGIN1Layout = new javax.swing.GroupLayout(iLOGIN1);
        iLOGIN1.setLayout(iLOGIN1Layout);
        iLOGIN1Layout.setHorizontalGroup(
            iLOGIN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iLOGIN1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(iLOGIN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtPassword)
                    .addGroup(iLOGIN1Layout.createSequentialGroup()
                        .addComponent(BtnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addComponent(TxtUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        iLOGIN1Layout.setVerticalGroup(
            iLOGIN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iLOGIN1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(iLOGIN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iLOGIN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iLOGIN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ?","Confirmation",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            System.exit(ok);
        }
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnMasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnMasukKeyPressed
        // TODO add your handling code here:
        aksi_login();
    }//GEN-LAST:event_BtnMasukKeyPressed

    private void BtnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasukActionPerformed
        // TODO add your handling code here:
        aksi_login();
    }//GEN-LAST:event_BtnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnMasuk;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private FORM.ILOGIN iLOGIN1;
    // End of variables declaration//GEN-END:variables
}
